swagger: "2.0"
info:
  description: API endpoint description
  version: "1.0.0"
  title: Swagger REST API definitions
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /contacts:
    get:
      operationId: "contacts.index"
      tags:
        - Contacts
      summary: "List of contacts"
      description: "Read the list of contacts"
      parameters:
        - name: page
          in: query
          type: integer
          description: The page number of the query
        - name: pagesize
          in: query
          type: integer
          description: The pagesize of the query
        - name: sortby
          in: query
          type: string
          description: Sort field
        - name: sortdir
          in: query
          type: string
          description: Sort direction
      responses:
        200:
          description: "Successful read of contacts"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  properties:
                    fname:
                      type: string
                    lname:
                      type: string
                    dob:
                      type: string
              page:
                type: integer
              pagesize:
                type: integer
              numberRecords:
                type: integer
    post:
      operationId: contacts.create
      tags:
        - Contacts
      summary: Create a new contact
      description: Create a new contact
      parameters:
        - name: contact
          in: body
          description: Contact to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: "string"
              lname:
                type: "string"
              dob:
                type: "string"
      responses:
        201:
          description: Successfully created contact
  /contacts/{oid}:
    get:
      operationId: contacts.read
      tags:
        - Contacts
      summary: Read one contact from the contacts list
      description: Read one contact from the contacts list
      parameters:
        - name: oid
          in: path
          description: id of the contact
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              dob:
                type: string
    put:
      operationId: contacts.update
      tags:
        - Contacts
      summary: Update a contact
      description: Update a contact
      parameters:
        - name: oid
          in: path
          description: id of the contact to update
          type: string
          required: True
        - name: contact
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
              lname:
                type: string
              dob:
                type: string
      responses:
        200:
          description: Successfully updated contact
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              dob:
                type: string
    delete:
      operationId: contacts.delete
      tags:
        - Contacts
      summary: Delete a contact
      description: Delete a contact
      parameters:
        - name: oid
          in: path
          description: id of the contact to update
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted contact
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              dob:
                type: string
  /contacts/{oid}/emails:
    get:
      operationId: emails.index
      tags:
        - Emails
      summary: Emails of the contact
      description: Get emails of the contact
      parameters:
        - name: oid
          in: path
          description: id of the contact to get the emails
          type: string
          required: True
      responses:
        200:
          description: Successful read of emails of contact
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  properties:
                    email:
                      type: string
              page:
                type: integer
              pagesize:
                type: integer
              numberRecords:
                type: integer
      
      
